// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  common: {
    actions: {
      remove: "Remove";
    };
    auth: {
      signIn: "Sign in";
      signOut: "Sign out";
    };
    locale: {
      enUS: "English (US)";
      esCO: "Spanish (Colombia)";
      esMX: "Spanish (Mexico)";
      label: "Language";
      saveError: "Unable to save language preference right now.";
    };
    status: {
      live: "Live";
    };
  };
  setup: {
    badges: {
      capacitySandbox: "Capacity sandbox";
      templateStarter: "Template starter";
      weeklyBoard: "Weekly board";
    };
    capacity: {
      fields: {
        appointmentDuration: "Appointment duration (min)";
        bookingHorizon: "Booking horizon (days)";
        leadTime: "Lead time (min)";
        slotStep: "Slot step (min)";
      };
      subtitle: "Tune constraints and inspect downstream capacity instantly.";
      title: "Capacity simulation";
    };
    cities: {
      bogota: "Bogota";
      cdmx: "CDMX";
    };
    days: {
      "0": "Sun";
      "1": "Mon";
      "2": "Tue";
      "3": "Wed";
      "4": "Thu";
      "5": "Fri";
      "6": "Sat";
    };
    errors: {
      client: {
        addWeeklyWindow: "Add at least one weekly window.";
        durationAndStepPositive: "Duration and slot step must be greater than 0.";
        integer: "{{field}} must be an integer.";
        leadTimeAndHorizon: "Lead time must be >= 0 and booking horizon must be > 0.";
        malformedTime: "Window {{index}} has malformed time. Use HH:MM (24h).";
        requiredNames: "Clinic name and provider name are required.";
        windowInvalidDay: "Window {{index}} has an invalid day.";
        windowOrder: "Window {{index}} must have start before end.";
        windowsOverlap: "Windows overlap on at least one day.";
      };
      fields: {
        appointmentDuration: "Appointment duration";
        bookingHorizon: "Booking horizon";
        leadTime: "Lead time";
        slotStep: "Slot step";
      };
      server: {
        setupAuthRequired: "Authentication is required.";
        setupClinicSlugEmpty: "Clinic slug cannot be empty after normalization.";
        setupInvalidPayload: "Invalid setup payload.";
        setupNumberInvalid: "One or more numeric fields are invalid.";
        setupWeeklyWindowInvalid: "One or more weekly windows are invalid.";
        setupWeeklyWindowOverlap: "Weekly schedule windows overlap on one or more days.";
        setupWeeklyWindowRequired: "At least one weekly schedule window is required.";
      };
      unknown: "Unable to save setup right now.";
    };
    header: {
      kicker: "Setup Studio";
      subtitle: "Template-driven week planning with live capacity what-if analysis.";
      title: "Planner + Simulator";
    };
    identity: {
      fields: {
        city: "City";
        clinicName: "Clinic name";
        providerName: "Provider name";
      };
      placeholders: {
        clinicName: "Clinica Centro";
        providerName: "Dr. Rivera";
      };
      timezoneLabel: "Timezone";
      title: "Identity + locale";
    };
    metrics: {
      horizonSlotEstimate: "Horizon slot estimate";
      slotsByStep: "Slots by step";
      visitsByDuration: "Visits by duration";
      weeklyOpenMinutes: "Weekly open minutes";
    };
    planner: {
      addWindowToDay: "Add window to {{day}}";
      daySummary: "{{count}} windows • {{minutes}} min";
      daySummary_many: "{{count}} windows • {{minutes}} min";
      daySummary_one: "{{count}} window • {{minutes}} min";
      daySummary_other: "{{count}} windows • {{minutes}} min";
      emptyFocusedDay: "No windows yet for this day.";
      fields: {
        end: "End (HH:MM)";
        start: "Start (HH:MM)";
      };
      focusedDay: "Focused day: {{day}}";
      moreWindows: "+{{count}} more";
      moreWindows_many: "+{{count}} more";
      moreWindows_one: "+{{count}} more";
      moreWindows_other: "+{{count}} more";
      subtitle: "Start with a template, sculpt by day, validate capacity live.";
      templateLabel: "Start from a schedule template";
      title: "Planner-simulator studio";
    };
    snapshot: {
      appointments: "{{scheduled}}/{{total}} scheduled";
      config: "{{duration}}m duration, {{step}}m step";
      empty: "Submit setup to fetch persisted clinic/provider data.";
      labels: {
        appointments: "Appointments";
        city: "City";
        clinic: "Clinic";
        config: "Config";
        provider: "Provider";
        timezone: "Timezone";
        windows: "Windows";
      };
      loading: "Loading snapshot...";
      missing: "No snapshot found.";
      title: "Saved snapshot";
    };
    submit: {
      saveSetup: "Save setup";
      saved: "Setup saved.";
      saving: "Saving...";
    };
    templates: {
      extended: {
        description: "Mon-Fri 08:00-18:00 + Sat 08:00-14:00";
        label: "Extended";
      };
      split: {
        description: "Mon-Fri 08:00-12:00 and 14:00-18:00";
        label: "Split shifts";
      };
      weekday: {
        description: "Mon-Fri 09:00-17:00";
        label: "Weekday standard";
      };
    };
    unauthenticated: {
      message: "Sign in to configure clinic and provider setup.";
    };
  };
}

export default Resources;
