/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as CallbackRouteImport } from "./routes/callback"
import { Route as AuthedRouteImport } from "./routes/_authed"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AuthedAppRouteImport } from "./routes/_authed/app"
import { Route as AuthedAppIndexRouteImport } from "./routes/_authed/app.index"
import { Route as AuthedAppSnapshotRouteImport } from "./routes/_authed/app.snapshot"
import { Route as AuthedAppSetupRouteImport } from "./routes/_authed/app.setup"
import { Route as AuthedAppAppointmentsRouteImport } from "./routes/_authed/app.appointments"

const CallbackRoute = CallbackRouteImport.update({
  id: "/callback",
  path: "/callback",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: "/app",
  path: "/app",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppIndexRoute = AuthedAppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppSnapshotRoute = AuthedAppSnapshotRouteImport.update({
  id: "/snapshot",
  path: "/snapshot",
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppSetupRoute = AuthedAppSetupRouteImport.update({
  id: "/setup",
  path: "/setup",
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppAppointmentsRoute = AuthedAppAppointmentsRouteImport.update({
  id: "/appointments",
  path: "/appointments",
  getParentRoute: () => AuthedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/callback": typeof CallbackRoute
  "/app": typeof AuthedAppRouteWithChildren
  "/app/appointments": typeof AuthedAppAppointmentsRoute
  "/app/setup": typeof AuthedAppSetupRoute
  "/app/snapshot": typeof AuthedAppSnapshotRoute
  "/app/": typeof AuthedAppIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/callback": typeof CallbackRoute
  "/app/appointments": typeof AuthedAppAppointmentsRoute
  "/app/setup": typeof AuthedAppSetupRoute
  "/app/snapshot": typeof AuthedAppSnapshotRoute
  "/app": typeof AuthedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_authed": typeof AuthedRouteWithChildren
  "/callback": typeof CallbackRoute
  "/_authed/app": typeof AuthedAppRouteWithChildren
  "/_authed/app/appointments": typeof AuthedAppAppointmentsRoute
  "/_authed/app/setup": typeof AuthedAppSetupRoute
  "/_authed/app/snapshot": typeof AuthedAppSnapshotRoute
  "/_authed/app/": typeof AuthedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/callback"
    | "/app"
    | "/app/appointments"
    | "/app/setup"
    | "/app/snapshot"
    | "/app/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/callback"
    | "/app/appointments"
    | "/app/setup"
    | "/app/snapshot"
    | "/app"
  id:
    | "__root__"
    | "/"
    | "/_authed"
    | "/callback"
    | "/_authed/app"
    | "/_authed/app/appointments"
    | "/_authed/app/setup"
    | "/_authed/app/snapshot"
    | "/_authed/app/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/callback": {
      id: "/callback"
      path: "/callback"
      fullPath: "/callback"
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authed": {
      id: "/_authed"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authed/app": {
      id: "/_authed/app"
      path: "/app"
      fullPath: "/app"
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/app/": {
      id: "/_authed/app/"
      path: "/"
      fullPath: "/app/"
      preLoaderRoute: typeof AuthedAppIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    "/_authed/app/snapshot": {
      id: "/_authed/app/snapshot"
      path: "/snapshot"
      fullPath: "/app/snapshot"
      preLoaderRoute: typeof AuthedAppSnapshotRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    "/_authed/app/setup": {
      id: "/_authed/app/setup"
      path: "/setup"
      fullPath: "/app/setup"
      preLoaderRoute: typeof AuthedAppSetupRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    "/_authed/app/appointments": {
      id: "/_authed/app/appointments"
      path: "/appointments"
      fullPath: "/app/appointments"
      preLoaderRoute: typeof AuthedAppAppointmentsRouteImport
      parentRoute: typeof AuthedAppRoute
    }
  }
}

interface AuthedAppRouteChildren {
  AuthedAppAppointmentsRoute: typeof AuthedAppAppointmentsRoute
  AuthedAppSetupRoute: typeof AuthedAppSetupRoute
  AuthedAppSnapshotRoute: typeof AuthedAppSnapshotRoute
  AuthedAppIndexRoute: typeof AuthedAppIndexRoute
}

const AuthedAppRouteChildren: AuthedAppRouteChildren = {
  AuthedAppAppointmentsRoute: AuthedAppAppointmentsRoute,
  AuthedAppSetupRoute: AuthedAppSetupRoute,
  AuthedAppSnapshotRoute: AuthedAppSnapshotRoute,
  AuthedAppIndexRoute: AuthedAppIndexRoute,
}

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(
  AuthedAppRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAppRoute: typeof AuthedAppRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppRoute: AuthedAppRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  CallbackRoute: CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
